name: Nix
on:
  push:
    branches:
      - main
      - dev
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      # TODO: add a binary cache
      # - uses: cachix/cachix-action@v10
      #   with:
      #     name: YOURCACHE
      #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check
        # Pre-build the system configuration
      #- run: nix build .#nixosConfigurations.targus
